name: Build revision-app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: msbuild -t:restore ./src/revision_app.csproj

    - name: Build
      run: msbuild ./src/revision_app.csproj /p:Configuration=Release /p:Platform=x64

    - name: Get commit SHA
      id: get-sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Show directory content
      id: get-directorycontent
      run: |
        echo "List files in ./src/bin/x64/Release/"
        ls ./src/bin/x64/Release/

    - name: Get file size
      id: get-size
      run: |
        $size = (Get-Item ./src/bin/x64/Release/RedefinedVision.exe).length / 1MB
        echo "::set-output name=size::$(("{0:N2}" -f $size))"

    - name: Rename output file
      run: |
        mv ./src/bin/x64/Release/RedefinedVision.exe ./src/bin/x64/Release/revision-${{ steps.get-sha.outputs.sha }}-${{ steps.get-size.outputs.size }}MB.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: revision-${{ steps.get-sha.outputs.sha }}-${{ steps.get-size.outputs.size }}
        path: ./src/bin/x64/Release/revision-${{ steps.get-sha.outputs.sha }}-${{ steps.get-size.outputs.size }}MB.exe
