name: Build revision-app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.x'

    - name: Restore dependencies
      run: msbuild -t:restore ./src/revision_app.csproj

    - name: Build
      run: msbuild ./src/revision_app.csproj /p:Configuration=Release /p:Platform=x64

    - name: Get commit SHA
      id: get-sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Get file size
      id: get-size
      run: |
        $size = (Get-Item ./src/bin/Release/revision_app.exe).length / 1MB
        echo "::set-output name=size::$(("{0:N2}" -f $size))"

    - name: Rename output file
      run: |
        mv ./src/bin/Release/revision_app.exe ./src/bin/Release/revision-${{ steps.get-sha.outputs.sha }}-${{ steps.get-size.outputs.size }}MB.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./src/bin/Release/revision-${{ steps.get-sha.outputs.sha }}-${{ steps.get-size.outputs.size }}MB.exe
